/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interactionmenu;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.stage.Stage;

public class App extends Application {

  @Override
  public void start(Stage primaryStage) throws Exception {
    // sample program with only one root node
    Group root = new Group();
    Scene scene = new Scene(root, 400, 400, Color.BLACK);
    // add a leaf node
    Circle cir = new Circle(200, 200, 100);
    cir.setFill(Color.CORAL);
    root.getChildren().add(cir);
    primaryStage.setTitle("JavaFX Scene Graph Example");
    primaryStage.setScene(scene);
    primaryStage.show();
  }

  public static void main(String[] args) {
    Application.launch(args);
  }
}
